apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-toto-MonApppp-backend-cert
  namespace: dev-toto-MonApppp-backend
spec:
  secretName: dev-toto-MonApppp-backend-tls
  dnsNames:
    - dev.testdomain.api.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
