apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-toto-MonApppp-backend-cert
  namespace: staging-toto-MonApppp-backend
spec:
  secretName: staging-toto-MonApppp-backend-tls
  dnsNames:
    - staging.testdomain.api.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
