apiVersion: v1
kind: Service
metadata:
  name: staging-toto-MonApppp-backend-service
  namespace: staging-toto-MonApppp-backend
spec:
  ports:
    - port: 3333
      targetPort: 3333
  selector:
    app: staging-toto-MonApppp-backend
