apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-toto-MonApppp-backend-cert
  namespace: prod-toto-MonApppp-backend
spec:
  secretName: prod-toto-MonApppp-backend-tls
  dnsNames:
    - testdomain.api.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
